### ISSUE TITLE
Filtering using current-path

### ISSUE THREAD

**Issue by pixelninja** [symphonists/expressionfield#1]
Apologies if this isn't an Expression Field issue, it could be Symphony related instead.

I am filtering a section based on $current-path to show certain content. This is working perfectly on subpages where current-path is something like `/foo`, but on the index page where current-path is '/', it is not returning the correct entry and just defaulting to the latest entry ID.

Any ideas? I've been away from Symphony for some time so I am quite rusty :s 

Symphony version 2.5.2 and Expression Field version 1.1

**Comment by brendo** [comment]
I'll take a look this evening, I have a project where I need to use this field so will check it out.

Are you using the 'regexp' setting?

**Comment by pixelninja** [comment]
Nah not using regexp.

Screenshots of setup, which has worked for me in the past. Shows entry values, and datasource filter.

![screen shot 2015-01-21 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/274397/5828877/bc0fd310-a16e-11e4-8852-5ae01b4e51bc.png)
![screen shot 2015-01-21 at 1 08 50 pm](https://cloud.githubusercontent.com/assets/274397/5828878/bc15079a-a16e-11e4-9728-1eb72da9c88b.png)

**Comment by brendo** [comment]
I"m going to use this field to do exactly what you are doing, navigation active states ;) Will let you know :)

**Comment by brendo** [comment]
Confirmed, I can reproduce the same result using Expression Field 1.1 and Symphony 2.6 (integration).

It's actually a [core bug](https://github.com/symphonycms/symphony-2/issues/1759)! The `/` gets evaluated as 'nothing' in the [Datasource](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.datasource.php#L311) class, so then the filter is unset!

**Comment by pixelninja** [comment]
Brilliant, thanks @brendo. I had a feeling it was core related. I have updated the class.datasource.php file as per your referenced Symphony commit and can confirm it is now working as expected.

Cheers mate!
